apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spill-av-im
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 24
    scalingStrategy:
      kafka:
        topic: tbd.rapid.v1
        consumerGroup: {{consumerGroupId}}
        threshold: 200
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  preStopHook:
    http:
      path: /stop
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafkaPool}}
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: {{databaseTier}}
        databases:
          - name: spillavim
            envVarPrefix: DATABASE
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{consumerGroupId}}
    - name: KAFKA_RESET_POLICY
      value: EARLIEST
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
