name: build

on:
  push:
    branches:
      - main
    paths:
      - 'matching/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - '.github/workflows/matching.yml'

env:
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: gradle
        run: ./gradlew :matching:build
      - name: Genererer versjon
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=8 HEAD)
          VERSION=$TIME-$COMMIT
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: upload artifacts
        run: ./gradlew :matching:publish -Pversion="$(echo $VERSION)"
        env:
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}